In [2]:
import numpy as np

***
## Problem:
What will be the shape of the following NumPy array?
```
arr = np.random.randint(1, 101, 100).reshape(10, -1)
```

In [ ]:
arr = np.random.randint(1,101, 100).reshape(10, -1)
print(arr.shape)

arr = np.random.randint(1,101, 100).reshape(20, -1)
print(arr.shape)
# randint takes two values for the range of random generated number and another for the number of elements
# reshape with a -1 indicates python to calculate the dimension based on the other dimension and total elements to calculate

*****
## Problem:
What is the result of the following code?

```
import numpy as np
A = np.array([1, 2, 3])
B = A * 2
```



In [ ]:
A = np.array([1, 2, 3])
B = A * 2
print(B)
# Numpy lets broadcast operations to the whole array

***
## Problem:
What does the following code output?

```
import numpy as np
matrix = np.eye(4)
result = np.diagonal(matrix)
print(result)
```


In [ ]:
matrix = np.eye(4)
result = np.diagonal(matrix)
print(result)

# np.eye() : NumPy function that creates identity matrix i.e a 2-D array with ones on the diagonal and zeros elsewhere.
# np.diagonal() : NumPy function used to extract the elements along the main diagonal of the matrix.


***
## Problem:
What is the result of the following code?

```
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = A.T
```

In [ ]:
A = np.array([[1, 2], [3, 4]])
print(A)
B = A.T
print(B)

# .T is an attribute of NumPy arrays that returns the transpose of the array.
# The transpose operation swaps the rows and columns of a matrix.

***
## Problem:
Which function can be used to concatenate two NumPy arrays horizontally?

In [ ]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8,9],[10,11,12]])
print(np.hstack((A, B))) # horizontal concatination
print("______________")
print(np.vstack((A,B))) # vertical concatination
print("______________")

# Same can be done using concatenate and an axis
print(np.concatenate((A,B), axis=1)) # horizontal concatination
print("______________")
print(np.concatenate((A,B), axis=0)) # vertical concatination


***
## Problem:
Which NumPy functions can be used to compute the element-wise multiplication of two arrays A and B?

In [ ]:
A = np.array([1,2,3])
B = np.array([4,5,6])
print(A*B)
print(np.multiply(A,B))

[ 4 10 18]
[ 4 10 18]


***
## Problem:
What is the result of the following code?

```
import numpy as np
A = np.array([10, 20, 30, 40])
mask = (A >= 20) & (A <= 30)
B = A[mask]
print(B)
```

In [ ]:
A = np.array([10, 20, 30, 40])
mask = (A >= 20) & (A <= 30)
B = A[mask]
print(B)

# Here, mask is a boolean array created based on the condition declared for the mask
# Similarly, lambdas can be used to create the mask.

[20 30]


***
## Problem:

Which NumPy function will return the indices of the minimum and maximum values in an array?







In [ ]:
A = np.random.randint(1, 100, 10) # Creating 1-D NumPy array of length 10 and element values randomly picked from 1 to 100

print(A)

print(np.argmin(A), " : ", np.min(A)) # index of max elem : max elem
print(np.argmax(A), "  : ", np.max(A)) # index of min elem : min elem

[39 92  1 81 90 60 18 40 86 14]
2  :  1
1   :  92


***
## Problem:

What is the output of the following code?

```
import numpy as np
arr = np.arange(1, 10).reshape(3, 3)
result = np.trace(arr)
print(result)
```

In [4]:
arr = np.arange(1, 10).reshape(3, 3)
print(arr)
result = np.trace(arr)
print(result)

# np.arange(1, 10, 2) : Similar to Python's built-in range() function but returns a NumPy array.
# np.trace(arr) : The trace is defined as the sum of the elements on the main diagonal of the matrix.

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


***
## Problem:
What is the output of the following code?

```
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.cross(arr1, arr2)
print(result)
```

In [7]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("Arr 1: ", arr1)
print("Arr 2: ", arr2)
result = np.cross(arr1, arr2)
print("Cross product of arr1 and arr2: ",result)

Arr 1:  [1 2 3]
Arr 2:  [4 5 6]
Cross product of arr1 and arr2:  [-3  6 -3]



* **np.cross(arr1, arr2)** : The cross product is a binary operation on two vectors in three-dimensional space.
* The result is another vector that is perpendicular to both of the input vectors.

***
## Problem:

***
## Problem:

***
## Problem:

Using NumPy, create a 1000-element array of random integers between 1 and 1000. Calculate the cumulative sum of the array and print the 10th, 100th, and 500th elements of the cumulative sum array.

In [ ]:
A = np.random.randint(1, 1001, 1000)
my_sum = np.cumsum(A)

print(my_sum[9])
print(my_sum[99])
print(my_sum[499])

Write a Python program using NumPy to create a 10x10 matrix filled with random integers between 1 and 100. Find the minimum and maximum values of the matrix along with their indices.

In [ ]:
A =  np.random.randint(1, 101, size =(10,10))
print(A)

min_val = np.min(A)
max_val = np.max(A)
print(min_val, max_val)

min_val_idx = np.argmin(A)
max_val_idx = np.argmax(A)
print(min_val_idx, max_val_idx)

min_idx = np.unravel_index(min_val_idx, A.shape)
max_idx = np.unravel_index(max_val_idx, A.shape)
print(min_idx, max_idx)

Write a Python program using NumPy to create a 5x5 matrix filled with random floats between 0 and 1. Replace the maximum value in the matrix with 0 and print the original and modified matrices.

In [ ]:
A = np.random.random(size=(5,5))
print(A)

max_idx = np.unravel_index(np.argmax(A), A.shape)
print(max_idx)

A[max_idx] = 0
print(A)

Given the following NumPy code, predict the output of the code:

In [ ]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = A[1:3, 0:2]
B[0, 0] = 100
print(A)

`[[  1   2   3]
 [100   5   6]
 [  7   8   9]]`

The change gets reflected in the original.

Two ways to slice:
1. view: B = A[1:3, 0:2].view()
2. copy: B = A[1:3, 0:2].copy()

By default, the view is shared.

In [ ]:
A = np.random.randint(1, 101, size=(20,))
print(A)

print(len(A[A%2 == 0]), len(A[A%2 == 1]))