## Importing the Numpy

In [ ]:
import numpy as np

## Broadcasting in NumPy

When operating on two arrays, NumPy compares their shapes element-wise. Its start with the trailing dimensions and works its way forward.

Two arrays A, B are compatible when:
* one of then is a singular value.
* one is R * C and the other is 1 * C
* one is R * C and the other is R * 1
* they have same shape

In [ ]:
# TODO two_d_arr + 10 ?
# TODO two_d_arr X one_d_horizontal_arr
# TODO two_d_arr / one_d_vertical_arr
# TODO two_d_arr + two_d_arr (compatibility required?)

In [ ]:
array_1 = np.array([1,2,3,4,5])

print(f"array_1 has {array_1.ndim} dimensions.")
print(f"array_1 has {array_1.shape} elements.")
print(array_1.size)
print(array_1.dtype)

In [ ]:
A = np.arange(12).reshape(3, 4)      # shape: (3, 4)
col = np.array([15, 25, 35])
row = np.array([10, 20, 30, 40])     # shape: (4,) -> treated as (1, 4)

print("A shape:", A.shape)
print("row shape:", row.shape)
print("A:\n", A)
print("row:", row)

C = col + row  # broadcasts row across rows
print("\nA + row (broadcast across rows) shape:", C.shape)
print(C)

In [ ]:
array_2 = np.array([1,2,3,4,5]
                   [6,7,8,9,10])

array_2.reshape(15, 1)

In [26]:
array_3 = np.array([[1,2,3,4,5],
                   [6,7,8,9,10],
                   [11,12,13,14,15]])

#array_3.reshape(15, -1)

array_3.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### Creating special arrays

In [27]:
# Identity matrix
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
np.random.rand(3,3)
print(np.random.rand(3,3))
print(np.random.randn(3,3))

[[0.80673178 0.3294159  0.06443953]
 [0.3103028  0.26180889 0.26407815]
 [0.10625878 0.0643403  0.85767482]]
[[-0.83692595 -0.00369671 -0.81754202]
 [-0.10833599  1.85900713 -1.45543321]
 [-0.18273506  0.78204544 -2.20164474]]


In [36]:
# TODO Concatenation : Vertical and Horizontal
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])
np.concatenate((x,y), axis = 0)

x= np.array([[1],[2]])
y = np.array([3], [4])
np.concatenate((x,y), axis = 1)

TypeError: Field elements must be 2- or 3-tuples, got '2'

In [38]:
print(x+y)
print(x-y)
print(x*y)
print(x/y)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


## Filtering in Numpy

## Saving to files in Numpy

## Slicing n-dimensional array